# ==============================================
# ⚡ Plugin Configuration - Ability & Lives System
# ==============================================

# Default player data values when they first join
default-data:
  lives: 5 # Default number of lives a player starts with
  streaks: 0 # Default kill streak count
  kill_marks: 0 # Kill markers (used for tracking progress)
  ability: "NONE" # Default ability (NONE means no ability assigned)

# if player has get the required give it as item not only level
give-kills-mark-as-item: false

# ==============================================
# 🎯 Ability Unlock System - Based on Kill Streaks
# ==============================================
abilities:
  - minStreak: 1
    maxStreak: 3
    ability: dash
    message: "🔥 You have taken Dash of Fury!"

  - minStreak: 3
    maxStreak: 5
    ability: charged_strike
    message: "⚡ Charged Strike unlocked!"

  - minStreak: 5
    maxStreak: 7
    ability: earthquake_slam
    message: "🌍 Earthquake Slam activated!"

  - minStreak: 7
    maxStreak: 9
    ability: rampage_surge
    message: "💖 Extra hearts & healing granted!"

  - minStreak: 9
    maxStreak: 12
    ability: thunderstrike
    message: "⚡ Thunderstrike unleashed!"

  - minStreak: 12
    maxStreak: 999
    ability: blinding_burst
    message: "✨ Ultimate Blinding Burst activated!"
# ==============================================
# ❤️ Lives System - Effects Based on Remaining Lives
# ==============================================
lives-system:
  - at: 5
    effect: "slowness" # Effect applied when a player has 5 lives
    message: "🚀 You feel lighter on your feet!"

  - at: 3
    effect: "weakness" # Effect applied when a player has 3 lives
    message: "🛡️ You gain slight resistance!"

  - at: 2
    effect: "mining_fatigue" # Effect applied when a player has 2 lives
    message: "💉 Your wounds begin to heal!"

  - at: 1
    effect: "jump_slow_fall" # Effect applied when a player has 1 life
    message: "💪 You feel a burst of strength in desperation!"

  - at: 0
    effect: "glowing_all" # No effect (could be death or respawn logic)
    message: "☠️ You have no more lives left!"

messages:
  enter-livesmode: "you have enterd lives mode becarefull"
  leave-livesmode: "you have left lives mode !"
