name: StreakBattles
main: me.a8kj.battlestreaks.plugin.BattleStreaksPlugin
author: a8kj7sea
api: "1.21.1"
version: "0.3"
api-version: "1.13"

commands:
  bsreload:
    description: Reload the plugin's configuration
    permission: bsplugin.reload
    permission-message: You do not have permission to use this command.
    aliases:
      - battlestreaskreload
      - strealsreload
      - bsrl
